- id: "xxxxxxx"
  alias: Putar Suara Adzan
  description: ""
  trigger:
    - platform: template
      value_template: '{{ states("sensor.time") == states("sensor.fajr") }}'
    - platform: template
      value_template: '{{ states("sensor.time") == states("sensor.dhuhr") }}'
    - platform: template
      value_template: '{{ states("sensor.time") == states("sensor.asr") }}'
    - platform: template
      value_template: '{{ states("sensor.time") == states("sensor.maghrib") }}'
    - platform: template
      value_template: '{{ states("sensor.time") == states("sensor.isha") }}'
  condition: []
  action:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.family_room #nama entity media player bisa menggunakan Google Home / Nest
        media_content_id: http://praytimes.org/audio/adhan/Sunni/Adhan%20Makkah.mp3 #URL file mp3 suara adzan
        media_content_type: audio/mp3
    - service: media_player.volume_set
      data:
        volume_level: "0.6"
      entity_id: media_player.family_room
  mode: single
