blueprint:
  name: Jadwal Adzan
  description: Putar Suara Adzan pada jam waktu sholat.
  domain: automation
  source_url: https://github.com/jharrvis/Jadwal-Sholat-Home-Assistant/blob/main/blueprints/automation/jadwal_sholat.yaml
    input:
    time_entity:
      name: Sensor Waktu
      selector:
        entity:
          domain: binary_sensor
          device_class: time
